
CREATE PROCEDURE SATISLAR
AS
SELECT SATISID,URUNAD,PERSONELAD+PERSONELSOYAD,MUSTERIAD+MUSTERISOYAD FROM	TBLSATIS
INNER JOIN TBLURUN ON TBLSATIS.URUN=TBLURUN.URUNID 
INNER JOIN TBLPERSONEL ON TBLSATIS.PERSONEL=TBLPERSONEL.PERSONELID
INNER JOIN TBLMUSTERI ON TBLSATIS.MUSTERI=TBLMUSTERI.MUSTERIID